name: rpg_world_env
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
    - pytest
    - pytest-mock
    - pyflakes
    - pycodestyle

# conda env create -f environment.yml
# conda env update --file environment.yml
# conda remove -n ENV_NAME --all
# conda env config vars set my_var=value

# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python

# use this to build and test my python package in github actions. write the yml for me. make sure that the test results and linter results must pass to allow a pr to be merged. 